server:
  port: 80


spring:
  profiles:
    active: gs
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: kr.co.doby.web.entity
  configuration:
    map-underscore-to-camel-case: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: uackD_jdVuDYz3doBWbK
            client-secret: AH339mCStX
            scope:
            - nickname
            - email
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/user/login/oauth2/code/naver

        provier:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response